version: '3.8'

services:
    php:
        build: .
        container_name: symfony_php
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        ports:
            - "9000:9000"

    nginx:
        image: nginx:alpine
        container_name: symfony_nginx
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
        depends_on:
            - php

    db:
        image: postgres:15
        container_name: symfony_db
        environment:
            POSTGRES_PASSWORD: 12345
            POSTGRES_USER: symfony
            POSTGRES_DB: symfony
        ports:
            - "5432:5432"
